### ISSUE TITLE
Aiuto per la Posizione file

### ISSUE THREAD

**Issue by Subia75** [skillaci86/Roborok-S5Max-Package#1]
Ciao,, complimenti per l'integrazione.
È da poco che ho il raspberry e non sono molto pratico. 
Vorrei provare a metterla nel mio HA, ma non so dove copiare i vari file tipo il pkg.roborock.yaml. 
Ti chiedo se fosse possibile un aiuto per copiare nelle giuste posizioni.
Grazie

**Comment by skillaci86** [comment]
Ciao solo ora ho letto la mail,
In queste settimane sono in vacanza appena rientro possiamo sentirci così
ti posso dare una mano a fare l integrazione



Il Ven 23 Lug 2021, 23:30 Alessio ***@***.***> ha scritto:

**Comment by Subia75** [comment]
grazie per la risposta.
se non ti secca un aiuto, volentieri.
Allora ti mando un promemoria qui verso fine agosto e buone vacanze.
